language: c

compiler:
    - clang
    - gcc

script:
    - mkdir build
    - cd build
    - cmake .. && make
    - ./unit_tests
    - gcov -o . src/nfe.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
